#ifndef COLORS__H
#define COLORS__H
# define RESET  "\x1b[0m"
# define BRIGHT  "\x1b[1m"
# define DIM  "\x1b[2m"
# define UNDERSCORE  "\x1b[4m"
# define BLINK  "\x1b[5m"
# define REVERSE  "\x1b[7m"
# define HIDDEN  "\x1b[8m"
# define BLACK  "\x1b[30m"
# define RED  "\x1b[31m"
# define GREEN  "\x1b[32m"
# define YELLOW  "\x1b[33m"
# define BLUE  "\x1b[34m"
# define MAGENTA  "\x1b[35m"
# define CYAN  "\x1b[36m"
# define WHITE  "\x1b[37m"
# define BGBLACK  "\x1b[40m"
# define BGRED  "\x1b[41m"
# define BGGREEN  "\x1b[42m"
# define BGYELLOW  "\x1b[43m"
# define BGBLUE  "\x1b[44m"
# define BGMAGENTA  "\x1b[45m"
# define BGCYAN  "\x1b[46m"
# define BGWHITE  "\x1b[47m"
#endif // !COLORS__H

